POST http://localhost:25114/Booongo/api/v1
Content-Type: application/json

{
  "name": "transaction",
  "uid": "9542f972e16b11e5b52c0242ac110010",
  "timestamp": "2022-01-16T22:25:02+00:00",
  "session": "4db895f0e0c911e58ac80242ac110009",
  "args": {
    "rounds": [
      3000123
    ],
    "freebet_id": null,
    "win": 50000,
    "bet": 30000,
    "token": "97a400c8964311ed9ca74ee79e92309e",
    "game": "green_chilli",
    "round_started": true,
    "round_finished": false,
    "award_id": null,
    "player": {
      "id": "cittestapmp77",
      "nick": "John",
      "currency": "KRW"
    }
  }
}