version: '3'
services:
  e-mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: hehe
    ports:
      - "27017:27017"
    volumes:
      - ./data-mongodb:/data/db
